Bagel.create!(name: "Everything")
Bagel.create!(name: "Poppyseed")
Bagel.create!(name: "Cinnamon Raisin")
Bagel.create!(name: "Whole Wheat")
Bagel.create!(name: "Plain")
Bagel.create!(name: "Blueberry")
Bagel.create!(name: "Salt")
Bagel.create!(name: "Garlic")
Bagel.create!(name: "Sesame")
Bagel.create!(name: "Onion")
Bagel.create!(name: "Pumpernickel")
Topping.create!(name: "Onion")
Topping.create!(name: "Tomato")
Topping.create!(name: "Lox")
Topping.create!(name: "Bacon")
Topping.create!(name: "Ham")
Topping.create!(name: "Strawberries")
Topping.create!(name: "Blueberries")
Topping.create!(name: "Bananas")
Topping.create!(name: "Avocado")
Topping.create!(name: "Tuna Salad")
Topping.create!(name: "Egg Salad")
Topping.create!(name: "Chicken Salad")
Topping.create!(name: "Steak")
Topping.create!(name: "Caviar")
Topping.create!(name: "Salmon")
Spread.create!(name: "Butter")
Spread.create!(name: "Plain Cream Cheese")
Spread.create!(name: "Strawberry Cream Cheese")
Spread.create!(name: "Pineapple Cream Cheese")
Spread.create!(name: "Scallion Cream Cheese")
Spread.create!(name: "Lite Cream Cheese")
Spread.create!(name: "Chive and Onion Cream Cheese")
Spread.create!(name: "Chipotle Cream Cheese")
Spread.create!(name: "Peanut Butter")
Spread.create!(name: "Jelly")
Spread.create!(name: "Yogurt")
Spread.create!(name: "Nutella")
User.create!(email: "chrislovesbagels@gmail.com", username: "chrislovesbagels", password: "password")